version: '3'

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
    name: laravel-backend

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel
    ports:
      - ${MYSQL_PORT:-33060}:3306
    volumes:
      - mysql-data:/var/lib/mysql:delegated
      - ./docker/mysql:/docker-entrypoint-initdb.d:delegated
      - ./docker/mysql/logs:/var/log/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: rootpass
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    depends_on:
      - app
